version: "3.7"

services:
  postgres:
    image: postgres:alpine
    ports:
      - published: 5433
        target: 5432
    environment:
      POSTGRES_DB: dockest-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
